spring.datasource.url=${DB_URL}
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.database=POSTGRESQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=${EMAIL_HOST}
spring.mail.port=${PORT}
spring.mail.username=${USER_EMAIL}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

springdoc.show-actuator=true
springdoc.swagger-ui.operationsSorter=method

app.security.jwt.secret-key=${SPRINT_SECRETKEY}

server.port = ${SERVER_PORT}
